# raise_error
workflow raise_errortest:
in:
	in string
out:
	out string
wfomap:
	out = v.thing
do:
	try:
		eval:
			thing = a.in x 2
		raise_error:
			msg = "let's raise an error"
	catch:
		eval:
			thing = 'caught error!'
